# Esto es un comentario.

# Utilizamos una imagen existente. Estas se encuentran en https://hub.docker.com/_/wordpress/
# Esta imagen requiere parámetros especificos para funcionar, por lo que leer la documentación es importante.
FROM wordpress:latest

# MAINTAINER indica quien es el autor del archivo docker.
MAINTAINER Alejandro Madrigal Leiva

# Variables de ambiente (los parámetros antes mencionados que previamente se usaban como parte del comando).
ENV WORDPRESS_DB_USER=root
ENV WORDPRESS_DB_PASSWORD=root
ENV WORDPRESS_DB_HOST=wordcamp_cr_2016_db
ENV WORDPRESS_DB_NAME=wordcampcr2016
